### ISSUE TITLE
Navigation not found

### ISSUE THREAD

**Issue by candrowm** [Viva-con-Agua/pool2-deployment-scripts#6]
Hello,

if i try to run the pool in dev mode, i got the following error message:

`martin@martin-VirtualBox:~/pool/pool2-deployment-scripts$ ./pool.sh dev setup
cat: /VERSION: Datei oder Verzeichnis nicht gefunden
use existing cert folder
8f42e197f34b711930c9fc2650ceb8ba9c3eba94b530fcada35d4ce680cdcc04
setup Drops database
810c8385df5821224399f5fb79d07d885ad98be28104af4f7d2ee77c88a7d148
b4f6c9d8c1e92fc19fdc12fc889c789cd0449f3b411cbbfe6f48dbcd50fbfc5e
setup dispenser database
b5fe70eba102930bd5c509432a82703c6a24d243518baf44a5cd4c0531dcfe14
setup dispesner
d08b82e7a7e57163fb0811b684743bc33750943376a0a268849693f27aaa19fe
dispenser
set Navigation
/home/martin/pool/pool2-deployment-scripts/scripts/dispenser.sh: Zeile 48: curl: Befehl nicht gefunden
setup Nats
313fcb367416db957bc878ed5bd7ad34a3c2b54e151cdad8a5d0b87eeb626362
setup Drops in dev mode
5562dff09ad534be46fc5615e96896b6abe7a0cda40f20533a54b17966ae17d3
setup Nginx in dev mode
59b8299af932f5230985514fde3e673071be794c1a11ea222459eda3f5c90fca
`

On http://localhost there is also an information that it can not find the navigation.

Best regards
Martin

**Comment by johannsell** [comment]
@deinelieblings can you take a look at this?

**Comment by deinelieblings** [comment]
`curl: Befehl nicht gefunden`  try to install curl

**Comment by johannsell** [comment]
`Curl` is used to import the base navigation into the database. So, this explains your error message.
